name: hogehoge
description: hogehoge
projects: ["ShotaroYuki/1"]
body:
  - type: markdown
    attributes:
      value: |
        ## 概要
        - 改善目的を記載する

        ## 詳細


        ## 工数見積もり
        - xxh
          - 時間は1,2,3,5,8,13...といったフィボナッチ数で入力
          - 13を超えてくるようだと、issueの粒度が大きい可能性があるので、さらに分解を検討するのがいいかもしれません

